name: "🏢 Company Task"
description: "A general task or responsibility on company level."
title: "🏢 [Task]: "
labels: []
assignees: []

body:
  - type: textarea
    id: task_description
    attributes:
      label: "📝 Describe the task"
      description: "What needs to be done?"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "📣 Reason / Event"
      description: "Why is this needed? What triggered this task?"

  - type: input
    id: due_date
    attributes:
      label: "📅 Due Date"
      description: "When should this be completed (optional)?"
      placeholder: "2025-07-15"
