blank_issues_enabled: false
contact_links: []
    
issue_templates:
  - name: "🐞 Bug Report"
    description: "Something is broken or behaves unexpectedly."
    file: bug_report.yml

  - name: "🛠 Feature Request"
    description: "A customer feature request"
    file: feature_request.yml
    
  - name: "🛠 General Feedback"
    description: "Tell us what you think!"
    file: general_feedback.yml
    