name: "✒ General Feedback"
description: "General Feedback to coldrock.games or this product"
title: "✒ [Feedback]: "
labels: []
assignees: []

body:
  - type: textarea
    id: feedback_content
    attributes:
      label: "✒ Feedback"
      description: "What is it, you like to tell us?"
      placeholder: "I miss the ability to..."
