name: "✒ Lore"
description: "Tell Me a Poem..."
title: "✒ [Lore]: "
labels: []
assignees: []

body:
  - type: dropdown
    id: poem_type
    attributes:
      label: "What kind of story is this?"
      options:
        - Game Background Story
        - Characters in the game
        - World/Area/Dungeon Story
        - Event Story
    validations:
      required: true

  - type: textarea
    id: story_content
    attributes:
      label: "📜 The Story Is About"
      description: "Content"
      placeholder: "Once upon a realm of shifting stars..."

  - type: textarea
    id: connects_to
    attributes:
      label: "🔗 Connects To / Related other lore"
      description: "What existing lore does this tie into?"
      placeholder: "It connects to the timeline of the Crimson Wars and the fall of House Iros."

  - type: textarea
    id: concept_art
    attributes:
      label: "🎨 Concept Art"
      description: "Rough ideas for how this could be visualized – sketches, shapes, moods, etc."
      placeholder: "Tall obsidian towers wrapped in mist, eyes blinking from the fog..."
