name: "✒ Lore Submission"
description: "Contribute a new story piece to the game's lore."
title: "✒ [Lore]: "
labels: ["lore"]
assignees: []

body:
  - type: checkboxes
    id: poem_type
    attributes:
      label: "📖 Tell Me a Poem..."
      description: "What kind of lore are you submitting?"
      options:
        - label: "Background Story"
        - label: "Characters in the game"
        - label: "Something else (please describe below)"

  - type: textarea
    id: other_topic
    attributes:
      label: "🗒️ Tell us about something else"
      description: "Only if you selected 'something else' above."
      placeholder: "This is about a forgotten race that lives under the dunes..."

  - type: textarea
    id: story_content
    attributes:
      label: "📜 The Story Is About"
      description: "What's the main content of this lore piece?"
      placeholder: "Once upon a realm of shifting stars..."

  - type: textarea
    id: must_have
    attributes:
      label: "⚠️ Don't Forget"
      description: "What elements must be included in this lore?"
      placeholder: "The goddess of fate must be mentioned at least once."

  - type: textarea
    id: connects_to
    attributes:
      label: "🔗 Connects To"
      description: "What existing lore does this tie into?"
      placeholder: "It connects to the timeline of the Crimson Wars and the fall of House Iros."

  - type: textarea
    id: concept_art
    attributes:
      label: "🎨 Concept Art"
      description: "Rough ideas for how this could be visualized – sketches, shapes, moods, etc."
      placeholder: "Tall obsidian towers wrapped in mist, eyes blinking from the fog..."

  - type: textarea
    id: additional_context
    attributes:
      label: "💬 Additional context"
      description: "Anything else we should know?"
      placeholder: "Inspired by Norse myths + Dune + that one fever dream last week."
