name: "📘 Story"
description: "A development story"
title: "📘 [Story]: "
labels: []
assignees: []

body:
  - type: textarea
    id: story_content
    attributes:
      label: "📝 The Story"
      description: "Write a little love letter to your favorite developer 💌"
      placeholder: "As a player, I want to be able to..."

  - type: textarea
    id: concept_art
    attributes:
      label: "🎨 Concept Art"
      description: "Sketch or describe how it should feel/look/work."

  - type: dropdown
    id: estimate
    attributes:
      label: "Estimated Size"
      description: "What's your best guess on the effort?"
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "omg! This is epic!"
